apiVersion: v1
kind: Service
metadata:
  name: bin-calendar
  namespace: ns-bin-calendar
spec:
  selector:
    app: bin-calendar
  ports:
    - protocol: TCP
      port: {{ .Values.port.source }}
      targetPort: {{ .Values.port.target }}
  type: LoadBalancer
